name: Code Quality Test
on: [push, pull_request]
jobs:
  Quality-Check:
    runs-on: ubuntu-22.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Check for os.system (#2)
        run: |
          git ls-files | xargs grep os.system
          exit $(git ls-files | xargs grep os.system | wc -l)